services:
  db:
    image: postgres:15
    container_name: bank_db
    restart: always
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: danylo-senchyshyn
      POSTGRES_PASSWORD: 3243
    ports:
      - "5432:5432"
    volumes:
      - bank_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: danylo-senchyshyn
      SPRING_DATASOURCE_PASSWORD: 3243
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JWT_SECRET: 2W5its7iTN0BSAdtlDa1Y1wmDu1CvNTHKl09teBZmCw=
      JWT_EXPIRATIONMS: 86400000
    depends_on:
      - db
    networks:
      - bank-network

volumes:
  bank_db_data:

networks:
  bank-network: