server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bank_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: 2W5its7iTN0BSAdtlDa1Y1wmDu1CvNTHKl09teBZmCw=
  expirationMs: 86400000  # 24 часа

logging:
  level:
    org.springframework: INFO
    com.example.bankcards: DEBUG